"""
This CLI plugin was auto-generated by using 'sonic-cli-gen' utility
"""

import click
import tabulate
import utilities_common.cli as clicommon


def format_attr_value(entry, attr):
    """ Helper that formats attribute to be presented in the table output.

    Args:
        entry (Dict[str, str]): CONFIG DB entry configuration.
        attr (Dict): Attribute metadata.

    Returns:
        str: fomatted attribute value.
    """

    if attr["is-leaf-list"]:
        value = entry.get(attr["name"], [])
        return "\n".join(value) if value else "N/A"
    return entry.get(attr["name"], "N/A")


@click.group(
    name="switch-hash",
    cls=clicommon.AliasedGroup
)
def SWITCH_HASH():
    """ Show switch hash feature configuration """

    pass


@SWITCH_HASH.command(
    name="global"
)
@clicommon.pass_db
def SWITCH_HASH_GLOBAL(db):
    """ Show switch hash global configuration """

    header = [
        "ECMP HASH",
        "LAG HASH",
    ]
    body = []

    table = db.cfgdb.get_table("SWITCH_HASH")
    entry = table.get("GLOBAL", {})

    if not entry:
        click.echo(tabulate.tabulate(body, header))
        return

    row = [
        format_attr_value(
            entry,
            {
                'name': 'ecmp_hash',
                'is-leaf-list': True
            }
        ),
        format_attr_value(
            entry,
            {
                'name': 'lag_hash',
                'is-leaf-list': True
            }
        ),
    ]
    body.append(row)

    click.echo(tabulate.tabulate(body, header))


def register(cli):
    """ Register new CLI nodes in root CLI.

    Args:
        cli (click.core.Command): Root CLI node.
    Raises:
        Exception: when root CLI already has a command
                   we are trying to register.
    """
    cli_node = SWITCH_HASH
    if cli_node.name in cli.commands:
        raise Exception(f"{cli_node.name} already exists in CLI")
    cli.add_command(SWITCH_HASH)
